p4 : stack.o queue.o p4.cpp
	g++ p4.cpp stack.o queue.o  -std=c++11 -Wall -g -o p4

stack.o : stack.h stack.cpp
	g++ stack.cpp               -std=c++11 -Wall -g -c

queue.o : queue.h queue.cpp
	g++ queue.cpp               -std=c++11 -Wall -g -c
